# Challenge - NumPy


![](https://images.unsplash.com/photo-1476525223214-c31ff100e1ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80)
Picture by [Jason Briscoe](https://unsplash.com/photos/HN_4K2diUWs)

Il s'agit d'un exercice où vous devrez passer un peu de temps à explorer la documentation de [NumPy documentation](https://numpy.org/doc/1.18/).

Pour installer numpy utilisez la commande suivante dans votre terminal :
`pip install numpy`

Sur macOS :
`pip3 install numpy`



Pour vous aider à réaliser ce TD, consultez et utilisez les fonctions suivantes :
- `import numpy as np`  : Pour importer la biblothèque numpy,
- `np.array([i1,i2,i3])` : Pour créer un vecteur contenant les éléments i1, i2 et i3,
- `np.zeros(n)`  : Pour créer un vecteur de taille n contenant uniquement des 0,
- `v[i]` : Pour obtenir la valeur à l'index i du vecteur v,
- `np.random.randint(n, m, k)` : Pour créer des vecteurs de taille k ayant des valeurs aléatoires comprises entre n (inclus) à m (exclus),
- `np.arange(n,m)`  :  Pour créer des vecteurs ayant des valeurs de n à m,
- `v.argmax()` : Pour trouver l'indice de la valeur maximale,
- `np.nonzero(n)`  : Pour créer des vecteurs de taille n,
- `v.reshape(n,m)` : Pour redimensionner un vecteur de taille n,m
- `np.eye(n)` : Pour créer une matrice identité de taille n,
- `np.nonzero(v)` : Pour trouver les indices des valeurs non nulles deu vecteur v, 
- `v.mean()` : Pour obtenir la moyenne d'un vecteur,
- `v.unique()` : Pour obtenir la liste des valeurs unique d'une matrice.
- `v[i] = u` : Pour assigner au vecteur `v` la valeur `u` à l'index `i`.

Où i, n, m et k sont des valeurs numériques entières.

**Q1**. Importez la librairie numpy.

In [2]:
import numpy as np

**Q2**. Créez un vecteur de taille 10 contenant uniquement des 0, la cinquième élément doit être 1. Les valeurs du tableau doivent être des `int`.

In [3]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**Q3**. Créez deux vecteurs aléatoires de taille 5, puis multipliez les vecteur entre-eux.

In [4]:
v1 = np.random.randint(0, 100, 5)
v2 = np.random.randint(0, 100, 5)
v1 * v2

array([ 352, 1936, 1785, 2044,  148])

**Q4**. Créez un vecteur avec des valeurs de 10 à 49 puis inversez l'ordre.

In [5]:
np.arange(10, 50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**Q5**. Créez un vecteur aléatoire de taille 10 et remplacez la valeur maximale par 0.

In [6]:
v = np.random.randint(0, 11, 10)
filtre = v == v.max()
v[filtre] = 0
v

array([0, 8, 4, 2, 4, 5, 0, 6, 8, 1])

**Q6**. Créez une matrice de taille 3x3 avec des valeurs allant de 0 à 8 inclus.

In [7]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Q7**. Créez une matrice d'identité de dimension et de rang 3x3.

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Q8**. Créez une matrice de dimension 30 et de rang 1 avec des valeurs entières aléatoires de 0 à 5 inclus. 
- Trouvez ensuite les indices d'éléments non nuls.

In [9]:
v = np.random.randint(0, 6,  30)
v

array([3, 0, 2, 3, 0, 3, 4, 0, 2, 0, 4, 1, 0, 5, 2, 4, 0, 5, 0, 4, 3, 1,
       0, 1, 2, 2, 5, 5, 2, 0])

In [10]:
v[v.nonzero()]

array([3, 2, 3, 3, 4, 2, 4, 1, 5, 2, 4, 5, 4, 3, 1, 1, 2, 2, 5, 5, 2])

**Q9**. Créez un matrice 10x10 avec des valeurs aléatoires et trouvez les valeurs minimales et maximales.

In [11]:
v = np.random.randint(100, size=(10,10))
print(v)
max = v.max()
print('max=' + str(max))

[[93  9 57 38 25 74 47 74 72 92]
 [33 46  4 43 91 33 39 31 71 98]
 [69 48 58 29 23 86 87 72 50 77]
 [41 99 66 81 95 61  6 34 84 74]
 [85 40  8 15 73 18  8 48 41 97]
 [32 88 91  6 30 18 15 75 99  2]
 [41 11  6 70 73 30 76 51 10 63]
 [99 62 50  5  8 79 83 24 65 44]
 [90 19 30 22 33 19  9  9  0 19]
 [36  0 54 61 71 11 42 19 41 56]]
max=99


In [12]:
min = v.min()
print('min=' + str(min))

min=0


**Q10**. Pour chaque ligne d'une matrice aléatoire de taille 5x10, soustrayez la moyenne de chaque ligne de cette matrice.

In [13]:
v = np.random.randint(0, 100, [5,10])
print(v)
for i in range(len(v)) :
    v[i] = v[i] - v[i].mean()
v

[[ 0 94 67 69 28 57 39 30 18 21]
 [84 80 93 74 78 18 41 35  6 58]
 [68 68 89 57 53 19 23 59 39 79]
 [54 20 87 40 33 99 56 75 27 23]
 [23  5  2 47 39 60 76 54 64 31]]


array([[-42,  51,  24,  26, -14,  14,  -3, -12, -24, -21],
       [ 27,  23,  36,  17,  21, -38, -15, -21, -50,   1],
       [ 12,  12,  33,   1,  -2, -36, -32,   3, -16,  23],
       [  2, -31,  35, -11, -18,  47,   4,  23, -24, -28],
       [-17, -35, -38,   6,  -1,  19,  35,  13,  23,  -9]])

**Q11 BONUS**. Ecrivez une fonction qui trouve la valeur la plus fréquente dans un tableau.

In [14]:
tab = np.random.randint(0,100, 30)
print(tab)
def find_most_elements(v):
    return np.bincount(v.flatten()).argmax()
find_most_elements(tab)

[76 37 18 86 60 26  7 57 83 17  2 29 57 31  0 63 48  3 62 68 81 15 93 66
  0 52 77 89 90 71]


0

**Q12BONUS**. Créez une matrice 10x10 avec la valeur 1 sur les bordures et 0 à l'intérieur.

In [15]:
tab = np.ones((10,10))
tab[1:-1, 1:-1] = 0
tab

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Q13BONUS**. Créez une matrice m3 de taille 8x8 puis remplissez-la avec un motif en damier (0,1).

**Q14BONUS**. Créez un vecteur v5 rempli de 30 valeurs entières aléatoires entre 1 et 10. Transformez en négatif les éléments qui sont entre 3 et 8.